### ISSUE TITLE
Log viewer hosted on Heroku suddenly doesn't start.

### ISSUE THREAD

**Issue by GolfingSuccess** [modmail-dev/logviewer#24]
This is what gets output to the Heroku logs:
```
2020-10-06T20:23:01.819134+00:00 heroku[worker.1]: State changed from crashed to starting
2020-10-06T20:23:05.573131+00:00 heroku[worker.1]: Starting process with command `python bot.py`
2020-10-06T20:23:06.173901+00:00 heroku[worker.1]: State changed from starting to up
2020-10-06T20:23:08.311811+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[117] - INFO: -------------------------
2020-10-06T20:23:08.311999+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[125] - INFO: Logging level: INFO
2020-10-06T20:23:08.312118+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[127] - INFO: Log file: /app/temp/NzM2NzE0NDkyODAwNTMyNTMx.log
2020-10-06T20:23:08.312476+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[91] - INFO: -------------------------
2020-10-06T20:23:08.312723+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[92] - INFO: ┌┬┐┌─┐┌┬┐┌┬┐┌─┐┬┬
2020-10-06T20:23:08.312921+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[93] - INFO: ││││ │ │││││├─┤││
2020-10-06T20:23:08.313110+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[94] - INFO: ┴ ┴└─┘─┴┘┴ ┴┴ ┴┴┴─┘
2020-10-06T20:23:08.313297+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[95] - INFO: v3.5.0
2020-10-06T20:23:08.313489+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[96] - INFO: Authors: kyb3r, fourjr, Taaku18
2020-10-06T20:23:08.313665+00:00 app[worker.1]: 10/06/20 20:23:08 __main__[97] - INFO: -------------------------
2020-10-06T20:23:08.984641+00:00 app[worker.1]: 10/06/20 20:23:08 core.clients[156] - WARNING: You're using the old config MONGO_URI, consider switching to the new CONNECTION_URI config.
2020-10-06T20:23:11.023211+00:00 app[worker.1]: 10/06/20 20:23:11 cogs.utility[606] - INFO: -------------------------
2020-10-06T20:23:11.023769+00:00 app[worker.1]: 10/06/20 20:23:11 cogs.utility[617] - INFO: No activity has been set.
2020-10-06T20:23:11.024026+00:00 app[worker.1]: 10/06/20 20:23:11 cogs.utility[622] - INFO: No status has been set.
2020-10-06T20:23:11.024308+00:00 app[worker.1]: 10/06/20 20:23:11 __main__[388] - ERROR: Logging out due to invalid GUILD_ID.
2020-10-06T20:23:11.132953+00:00 app[worker.1]: 10/06/20 20:23:11 cogs.plugins[143] - ERROR: Error when loading plugin officialpiyush/modmail-plugins/giveaway@master. Plugin removed from config.
2020-10-06T20:23:11.132954+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-06T20:23:11.132954+00:00 app[worker.1]:   File "/app/cogs/plugins.py", line 136, in initial_load_plugins
2020-10-06T20:23:11.132955+00:00 app[worker.1]:     await self.download_plugin(plugin)
2020-10-06T20:23:11.132955+00:00 app[worker.1]:   File "/app/cogs/plugins.py", line 166, in download_plugin
2020-10-06T20:23:11.132955+00:00 app[worker.1]:     async with self.bot.session.get(plugin.url, headers=headers) as resp:
2020-10-06T20:23:11.132956+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
2020-10-06T20:23:11.132956+00:00 app[worker.1]:     self._resp = await self._coro
2020-10-06T20:23:11.132956+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
2020-10-06T20:23:11.132957+00:00 app[worker.1]:     timeout=real_timeout
2020-10-06T20:23:11.132958+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
2020-10-06T20:23:11.132958+00:00 app[worker.1]:     proto = await self._create_connection(req, traces, timeout)
2020-10-06T20:23:11.132958+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
2020-10-06T20:23:11.132958+00:00 app[worker.1]:     req, traces, timeout)
2020-10-06T20:23:11.132959+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
2020-10-06T20:23:11.132959+00:00 app[worker.1]:     req=req, client_error=client_error)
2020-10-06T20:23:11.132959+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
2020-10-06T20:23:11.132960+00:00 app[worker.1]:     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
2020-10-06T20:23:11.132960+00:00 app[worker.1]:   File "uvloop/loop.pyx", line 2019, in create_connection
2020-10-06T20:23:11.132960+00:00 app[worker.1]:   File "uvloop/loop.pyx", line 2014, in uvloop.loop.Loop.create_connection
2020-10-06T20:23:11.132960+00:00 app[worker.1]: concurrent.futures._base.CancelledError
2020-10-06T20:23:11.134899+00:00 app[worker.1]: 10/06/20 20:23:11 __main__[178] - ERROR:  - Shutting down bot - 
2020-10-06T20:23:11.605072+00:00 heroku[worker.1]: Process exited with status 0
2020-10-06T20:23:11.633285+00:00 heroku[worker.1]: State changed from up to crashed
```
I hadn't changed anything since I initially set it up and it was working. However, nowadays, the bot.py worker is asking me for the bot's token (in a separate instance not in this log), which I find weird... anyway, I put the `TOKEN` in as a config var and this showed up. I can't quite figure out what the error is. Thanks in advance! TBF, it kinda looks like this is the worker for the bot and not the logs...

**Comment by RealCyGuy** [comment]
This is the bot's logs, not the logviewer's logs.

**Comment by GolfingSuccess** [comment]
So... just realized I made this, the issue was that modmail's structure had updated so `bot.py` was being invoked, I had to reconfigure the heroku apps... so, I'm closing this out.
